seed: 233
log_dir: null
print_freq: 100 # steps

config_file: null
init_file: null

task:
    data_key: null
    data_root: null
    target: energy
    regress_force: False
    standardize: True
    add_noise: False
    noise_params: null

model:
    name: null
    num_blocks: 4
    hidden_channels: 128
    out_channels: 1
    int_emb_size: 64
    basis_emb_size: 16
    out_emb_channels: 256
    num_spherical: 8
    num_radial: 6
    envelope_exponent: 5
    max_num_neighbors: 32
    cutoff: 5.0
    num_before_skip: 1
    num_after_skip: 2
    num_output_layers: 3

dataloader:
    batch_size: 128
    eval_batch_size: 256
    num_workers: 8
    pin_memory: True

optim:
    optimizer: AdamW
    optimizer_params:
        weight_decay: 0.0001
    lr_initial: 0.0008
    scheduler: LambdaLR
    scheduler_params:
        lambda_type: cosine
        warmup_factor: 0.2
        warmup_epochs: 0.01 #
        lr_min_factor: 0.01

    # grad_accumulation_steps: 1
    clip_grad_norm: 10

    max_epochs: 300
    energy_coefficient: 1
    force_coefficient: 10
    loss_energy: mae
    loss_force: mae

    ema: False
    ema_decay: 0.999
    eval_every: 5000
